version: '3'

services:
  asterisk-16-ari:
    image: rjp44/asterisk-16-ari
    restart: unless-stopped
    container_name: asterisk-16-ari
    ports:
      - "5061:5061"
      - "8080:8080"
      - "8443:8443"
    env_file:
      - ../asterisk.env